
// Auto-generated by AutoPilot on 16-08-2023 at 01:14:07

const express = require('express');
const router = express.Router();

// This route will return the review for the movie Mission Impossible 1
router.get('/review', (req, res) => {
    res.json({"review": "Mission Impossible 1 is an action packed movie with Tom Cruise delivering an amazing performance. The movie is full of suspense and thrilling moments, making it a great watch. I would rate it 10 on 10!"});
});

module.exports = router;